### ISSUE TITLE
Can not detect Drupal version cause it stops iterating when one of the possible URLs gets a 200 response 

### ISSUE THREAD

**Issue by iammyr** [dreadlocked/Drupalgeddon2#49]
If any of the URLs referred to in order to guess the Drupal version returns 200, even though given the response body does not allow to actually determine the version, the iteration stops (break).
Therefore, the next URLs are never checked.

**Comment by iammyr** [comment]
proposed fix https://github.com/dreadlocked/Drupalgeddon2/pull/50

**Comment by g0tmi1k** [comment]
*merged*
