### ISSUE TITLE
Feature Request: Control verbosity via Command-Line Argument

### ISSUE THREAD

**Issue by iammyr** [dreadlocked/Drupalgeddon2#51]
Currently the verbosity level is hard-coded. It would be useful to control it via command-line argument.

**Comment by iammyr** [comment]
Proposed fix https://github.com/dreadlocked/Drupalgeddon2/commit/3275deb08137cce7991a5b87742d71cc3131e8a9 

(would it be possible to mark this issue with the label "hacktoberfest", please? Thanks a million!)

**Comment by g0tmi1k** [comment]
*merged*
