### ISSUE TITLE
Feature Request: Support for Session-Cookie Form and POST-based Authentication

### ISSUE THREAD

**Issue by iammyr** [dreadlocked/Drupalgeddon2#52]
Support for exploting a website protected by authentication 

- via web form 
- submitted via POST request 
- eventually requiring form ID and/or other constant values appended to the credentials
- returning a session cookie to use in all subsequent requests

**Comment by iammyr** [comment]
proposed fix at https://github.com/dreadlocked/Drupalgeddon2/pull/50/commits/3f06f77acc46fbc419492b4ca79837c55c4dd920

(would it be possible to mark this issue with the label "hacktoberfest", please? Thanks a million!)

**Comment by g0tmi1k** [comment]
*merged*
