### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by 0ktavandi** [dreadlocked/Drupalgeddon2#55]
Traceback (most recent call last):
	2: from drupalgeddon2.rb:16:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- highline/import (LoadError)

**Comment by g0tmi1k** [comment]
Could you provide more information on your setup?

What's the OS? What version any/all the software you are using?
What command did you run?
Where did it say the output?

**Comment by 4nakata** [comment]
Same problem
OS : Ubuntu 16.04 X64
Ruby version : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
command: ruby drup2.rb host.com
output : 
`Traceback (most recent call last):
	2: from drup2.rb:16:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- highline/import (LoadError)
`

**Comment by iammyr** [comment]
everyone:
you need to run `sudo gem install highline`
and do the above for any future missing dependencies

**Comment by dreadlocked** [comment]
Pull request accepted for this kind of issues https://github.com/dreadlocked/Drupalgeddon2/pull/57.

Closing this issue.
