### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kalimon12** [dreadlocked/Drupalgeddon2#61]
Traceback (most recent call last):
	2: from drupalgeddon2.rb:16:in `<main>'
	1: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- highline/import (LoadError)

**Comment by g0tmi1k** [comment]
Please re-open and and when you do provide more infomation?
OS? Version? Platform? Arch? What version of the script? How did you install? What command did you run?
