### ISSUE TITLE
Not working for me :( please help!!

### ISSUE THREAD

**Issue by Devilemox** [dreadlocked/Drupalgeddon2#62]
![Screenshot from 2019-08-28 13-59-20](https://user-images.githubusercontent.com/43777071/63839050-1f605980-c99c-11e9-9aab-b552928c000b.png)

I tried to run this and it give back this error!! What to do??

**Comment by kenorb** [comment]
You're missing `highline` gem as per message. Try installing it:

```
sudo gem install highline
```

**Comment by g0tmi1k** [comment]
Like @kenorb said, and its also converted in the readme.

**Comment by Devilemox** [comment]
sorry about that.. :P
